// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codegen

import (
	"time"

	imetrics "github.com/eberkley/weaver/internal/metrics"
	"github.com/eberkley/weaver/metrics"
)

var LatencyBuckets []float64 = make([]float64, 0)

var (
	// The following metrics are automatically populated for the user.
	methodCounts = metrics.NewCounterMap[MethodLabels](
		imetrics.MethodCountsName,
		"Count of Service Weaver component method invocations",
	)
	methodErrors = metrics.NewCounterMap[MethodLabels](
		imetrics.MethodErrorsName,
		"Count of Service Weaver component method invocations that result in an error",
	)
	methodBytesRequest = metrics.NewHistogramMap[MethodLabels](
		imetrics.MethodBytesRequestName,
		"Number of bytes in Service Weaver component method requests",
		imetrics.GeneratedBuckets,
	)
	methodBytesReply = metrics.NewHistogramMap[MethodLabels](
		imetrics.MethodBytesReplyName,
		"Number of bytes in Service Weaver component method replies",
		imetrics.GeneratedBuckets,
	)

	methodLatencies         *metrics.HistogramMap[MethodLabels]
	internalMethodLatencies *metrics.HistogramMap[InternalMethodLabels]

	internalStartedMethods = metrics.NewCounterMap[InternalMethodLabels](
		imetrics.StartedMethodsName,
		"Number of concurrently executing calls to a given method.",
	)
	internalFinishedMethods = metrics.NewCounterMap[InternalMethodLabels](
		imetrics.FinishedMethodsName,
		"Number of concurrently executing calls to a given method.",
	)

	goroutineGauge = metrics.NewGaugeMap[ComponentLabels](
		imetrics.GroupGoroutineName,
		"Number of goroutines in the Service Weaver component",
	)
)

func init() {
	LatencyBuckets = make([]float64, 1)
	LatencyBuckets[0] = 1

	for l := 25.0; l < 250; l += 25 {
		LatencyBuckets = append(LatencyBuckets, l) // 25us - 250us: 25us
	}
	for l := 250.0; l < 1_000; l += 50 {
		LatencyBuckets = append(LatencyBuckets, l) // 250us - 1ms: 50us
	}
	for l := 1_000.0; l < 2_000; l += 100 {
		LatencyBuckets = append(LatencyBuckets, l) // 1ms - 2ms: 100us
	}
	for l := 2_000.0; l < 20_000; l += 250 {
		LatencyBuckets = append(LatencyBuckets, l) // 2ms - 20ms: 250us
	}
	for l := 20_000.0; l < 100_000; l += 1_000 {
		LatencyBuckets = append(LatencyBuckets, l) // 20ms - 100ms: 1ms
	}
	LatencyBuckets = append(LatencyBuckets, 100_000.0, 150_000.0, 250_000.0, 1_000_000.0)

	methodLatencies = metrics.NewHistogramMap[MethodLabels](
		imetrics.MethodLatenciesName,
		"Duration, in microseconds, of Service Weaver component method execution",
		LatencyBuckets,
	)

	internalMethodLatencies = metrics.NewHistogramMap[InternalMethodLabels](
		imetrics.InternalMethodLatenciesName,
		"Internal method duration",
		LatencyBuckets,
	)
}

type MethodLabels struct {
	Caller    string // full calling component name
	Component string // full callee component name
	Method    string // callee component method's name
	Remote    bool   // Is this a remote call?
	Generated bool   `weaver:"serviceweaver_generated"` // Is this an autogenerated metric?
}

// MethodMetrics contains metrics for a single Service Weaver component method.
type MethodMetrics struct {
	remote       bool
	count        *metrics.Counter   // See MethodCounts.
	errorCount   *metrics.Counter   // See MethodErrors.
	latency      *metrics.Histogram // See MethodLatencies.
	bytesRequest *metrics.Histogram // See MethodBytesRequest.
	bytesReply   *metrics.Histogram // See MethodBytesReply.
	started      *metrics.Counter
	finished     *metrics.Counter
	// concurrency  *metrics.Gauge
}

type InternalMethodLabels struct {
	Remote    bool
	Caller    string
	Component string
	Method    string
}

type ConcurrentMethodMetrics struct {
	started  *metrics.Counter
	finished *metrics.Counter
}

type ComponentLabels struct {
	Component string
}

func GroupGoroutineFor(labels ComponentLabels) *metrics.Gauge {
	return goroutineGauge.Get(labels)
}

func InternalConcurrentMetricsFor(labels InternalMethodLabels) *ConcurrentMethodMetrics {
	labels.Remote = false
	labels.Caller = "*"
	return &ConcurrentMethodMetrics{
		started:  internalStartedMethods.Get(labels),
		finished: internalFinishedMethods.Get(labels),
	}
}

func (c *ConcurrentMethodMetrics) Begin() { c.started.Inc() }
func (c *ConcurrentMethodMetrics) End()   { c.finished.Inc() }

func InternalMetricsFor(labels InternalMethodLabels) *metrics.Histogram {
	return internalMethodLatencies.Get(labels)
}

// MethodMetricsFor returns metrics for the specified method.
func MethodMetricsFor(labels MethodLabels) *MethodMetrics {
	label := InternalMethodLabels{Remote:labels.Remote, Caller: labels.Caller, Component: labels.Component, Method: labels.Method}
	return &MethodMetrics{
		remote:       labels.Remote,
		count:        methodCounts.Get(labels),
		errorCount:   methodErrors.Get(labels),
		latency:      methodLatencies.Get(labels),
		bytesRequest: methodBytesRequest.Get(labels),
		bytesReply:   methodBytesReply.Get(labels),
		started:      internalStartedMethods.Get(label),
		finished:     internalFinishedMethods.Get(label),
	}
}

// MethodCallHandle holds information needed to finalize metric
// updates for a method call.
type MethodCallHandle struct {
	start time.Time
}

// Begin starts metric update recording for a call to method m.
func (m *MethodMetrics) Begin() MethodCallHandle {
	m.started.Inc()
	return MethodCallHandle{time.Now()}
}

// End ends metric update recording for a call to method m.
func (m *MethodMetrics) End(h MethodCallHandle, failed bool, requestBytes, replyBytes int) {
	latency := time.Since(h.start).Microseconds()
	m.finished.Inc()
	m.count.Inc()
	if failed {
		m.errorCount.Inc()
	}
	m.latency.Put(float64(latency))
	if m.remote {
		m.bytesRequest.Put(float64(requestBytes))
		m.bytesReply.Put(float64(replyBytes))
	}
}
