// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package bank

import (
	"context"
	"errors"
	"github.com/eberkley/weaver"
	"github.com/eberkley/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/eberkley/weaver/sim/internal/bank/Bank",
		Iface: reflect.TypeOf((*Bank)(nil)).Elem(),
		Impl:  reflect.TypeOf(bank{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return bank_local_stub{impl: impl.(Bank), tracer: tracer, depositMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Deposit", Remote: false, Generated: true}), withdrawMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Withdraw", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return bank_client_stub{stub: stub, depositMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Deposit", Remote: true, Generated: true}), withdrawMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Withdraw", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return bank_server_stub{impl: impl.(Bank), addLoad: addLoad, depositMetrics: codegen.InternalConcurrentMetricsFor(codegen.InternalMethodLabels{Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Deposit"}), withdrawMetrics: codegen.InternalConcurrentMetricsFor(codegen.InternalMethodLabels{Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Withdraw"})}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return bank_reflect_stub{caller: caller}
		},
		RoutedLocalStubFn: func(impl any, stub codegen.Stub, caller string, tracer trace.Tracer, isLocal func(shardKey uint64) bool) any {
			return bank_routed_local_stub{impl: impl.(Bank), stub: stub, tracer: tracer, isLocal: isLocal, depositMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Deposit", Remote: true, Generated: true}), withdrawMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Bank", Method: "Withdraw", Remote: true, Generated: true})}
		},
		RefData: "⟦98acde42:wEaVeReDgE:github.com/eberkley/weaver/sim/internal/bank/Bank→github.com/eberkley/weaver/sim/internal/bank/Store⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "github.com/eberkley/weaver/sim/internal/bank/Store",
		Iface: reflect.TypeOf((*Store)(nil)).Elem(),
		Impl:  reflect.TypeOf(store{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return store_local_stub{impl: impl.(Store), tracer: tracer, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Add", Remote: false, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Get", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return store_client_stub{stub: stub, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Add", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Get", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return store_server_stub{impl: impl.(Store), addLoad: addLoad, addMetrics: codegen.InternalConcurrentMetricsFor(codegen.InternalMethodLabels{Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Add"}), getMetrics: codegen.InternalConcurrentMetricsFor(codegen.InternalMethodLabels{Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Get"})}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return store_reflect_stub{caller: caller}
		},
		RoutedLocalStubFn: func(impl any, stub codegen.Stub, caller string, tracer trace.Tracer, isLocal func(shardKey uint64) bool) any {
			return store_routed_local_stub{impl: impl.(Store), stub: stub, tracer: tracer, isLocal: isLocal, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Add", Remote: true, Generated: true}), getMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/eberkley/weaver/sim/internal/bank/Store", Method: "Get", Remote: true, Generated: true})}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[Bank] = (*bank)(nil)
var _ weaver.InstanceOf[Store] = (*store)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*bank)(nil)
var _ weaver.Unrouted = (*store)(nil)

// Local stub implementations.

type bank_local_stub struct {
	impl            Bank
	tracer          trace.Tracer
	depositMetrics  *codegen.MethodMetrics
	withdrawMetrics *codegen.MethodMetrics
}

// Check that bank_local_stub implements the Bank interface.
var _ Bank = (*bank_local_stub)(nil)

func (s bank_local_stub) Deposit(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	begin := s.depositMetrics.Begin()
	defer func() { s.depositMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "bank.Bank.Deposit", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Deposit(ctx, a0, a1)
}

func (s bank_local_stub) Withdraw(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	begin := s.withdrawMetrics.Begin()
	defer func() { s.withdrawMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "bank.Bank.Withdraw", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Withdraw(ctx, a0, a1)
}

type store_local_stub struct {
	impl       Store
	tracer     trace.Tracer
	addMetrics *codegen.MethodMetrics
	getMetrics *codegen.MethodMetrics
}

// Check that store_local_stub implements the Store interface.
var _ Store = (*store_local_stub)(nil)

func (s store_local_stub) Add(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "bank.Store.Add", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Add(ctx, a0, a1)
}

func (s store_local_stub) Get(ctx context.Context, a0 string) (r0 int, err error) {
	// Update metrics.
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "bank.Store.Get", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Get(ctx, a0)
}

// Client stub implementations.

type bank_client_stub struct {
	stub            codegen.Stub
	depositMetrics  *codegen.MethodMetrics
	withdrawMetrics *codegen.MethodMetrics
}

// Check that bank_client_stub implements the Bank interface.
var _ Bank = (*bank_client_stub)(nil)

func (s bank_client_stub) Deposit(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.depositMetrics.Begin()
	defer func() { s.depositMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "bank.Bank.Deposit", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.Int(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Int()
	err = dec.Error()
	return
}

func (s bank_client_stub) Withdraw(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.withdrawMetrics.Begin()
	defer func() { s.withdrawMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "bank.Bank.Withdraw", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.Int(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Int()
	err = dec.Error()
	return
}

type store_client_stub struct {
	stub       codegen.Stub
	addMetrics *codegen.MethodMetrics
	getMetrics *codegen.MethodMetrics
}

// Check that store_client_stub implements the Store interface.
var _ Store = (*store_client_stub)(nil)

func (s store_client_stub) Add(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "bank.Store.Add", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.Int(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Int()
	err = dec.Error()
	return
}

func (s store_client_stub) Get(ctx context.Context, a0 string) (r0 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetrics.Begin()
	defer func() { s.getMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "bank.Store.Get", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Int()
	err = dec.Error()
	return
}

// Routed local stub implementations.

type bank_routed_local_stub struct {
	impl            Bank
	stub            codegen.Stub
	tracer          trace.Tracer
	isLocal         func(shardKey uint64) bool
	depositMetrics  *codegen.MethodMetrics
	withdrawMetrics *codegen.MethodMetrics
}

// Check that bank_routed_local_stub implements the Bank interface.
var _ Bank = (*bank_routed_local_stub)(nil)

func (s bank_routed_local_stub) Deposit(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = errors.New("can not call routed local method on unrouted component")
	err = errors.Join(weaver.RemoteCallError, err)
	return
}

func (s bank_routed_local_stub) Withdraw(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = errors.New("can not call routed local method on unrouted component")
	err = errors.Join(weaver.RemoteCallError, err)
	return
}

type store_routed_local_stub struct {
	impl       Store
	stub       codegen.Stub
	tracer     trace.Tracer
	isLocal    func(shardKey uint64) bool
	addMetrics *codegen.MethodMetrics
	getMetrics *codegen.MethodMetrics
}

// Check that store_routed_local_stub implements the Store interface.
var _ Store = (*store_routed_local_stub)(nil)

func (s store_routed_local_stub) Add(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = errors.New("can not call routed local method on unrouted component")
	err = errors.Join(weaver.RemoteCallError, err)
	return
}

func (s store_routed_local_stub) Get(ctx context.Context, a0 string) (r0 int, err error) {
	err = errors.New("can not call routed local method on unrouted component")
	err = errors.Join(weaver.RemoteCallError, err)
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.25.2-0.20250419001101-42f7bf3eb269+dirty (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/eberkley/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/eberkley/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/eberkley/weaver@latest
    go install github.com/eberkley/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/eberkley/weaver/issues.

`)

// Server stub implementations.

type bank_server_stub struct {
	impl            Bank
	addLoad         func(key uint64, load float64)
	depositMetrics  *codegen.ConcurrentMethodMetrics
	withdrawMetrics *codegen.ConcurrentMethodMetrics
}

// Check that bank_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*bank_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s bank_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Deposit":
		return s.deposit
	case "Withdraw":
		return s.withdraw
	default:
		return nil
	}
}

func (s bank_server_stub) deposit(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()
	s.depositMetrics.Begin()
	defer s.depositMetrics.End()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 int
	a1 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Deposit(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Int(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s bank_server_stub) withdraw(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()
	s.withdrawMetrics.Begin()
	defer s.withdrawMetrics.End()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 int
	a1 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Withdraw(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Int(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type store_server_stub struct {
	impl       Store
	addLoad    func(key uint64, load float64)
	addMetrics *codegen.ConcurrentMethodMetrics
	getMetrics *codegen.ConcurrentMethodMetrics
}

// Check that store_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*store_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s store_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Add":
		return s.add
	case "Get":
		return s.get
	default:
		return nil
	}
}

func (s store_server_stub) add(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()
	s.addMetrics.Begin()
	defer s.addMetrics.End()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 int
	a1 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Add(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Int(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s store_server_stub) get(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()
	s.getMetrics.Begin()
	defer s.getMetrics.End()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Get(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Int(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type bank_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that bank_reflect_stub implements the Bank interface.
var _ Bank = (*bank_reflect_stub)(nil)

func (s bank_reflect_stub) Deposit(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = s.caller("Deposit", ctx, []any{a0, a1}, []any{&r0})
	return
}

func (s bank_reflect_stub) Withdraw(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = s.caller("Withdraw", ctx, []any{a0, a1}, []any{&r0})
	return
}

type store_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that store_reflect_stub implements the Store interface.
var _ Store = (*store_reflect_stub)(nil)

func (s store_reflect_stub) Add(ctx context.Context, a0 string, a1 int) (r0 int, err error) {
	err = s.caller("Add", ctx, []any{a0, a1}, []any{&r0})
	return
}

func (s store_reflect_stub) Get(ctx context.Context, a0 string) (r0 int, err error) {
	err = s.caller("Get", ctx, []any{a0}, []any{&r0})
	return
}
